kind: ConfigMap
apiVersion: v1
metadata:
  name: backend
  namespace: expense
data:
    DB_HOST: mysql
---
apiVersion: v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    tier: api
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      tier: api
      project: expense
  template:
    metadata:
      labels:
        app: backend
        tier: api  
        project: expense
    spec:
      containers:
      - name: backend
        image: rajikakani412/backend:v1
        envFrom:
        - configMapRef:
            name: backend
---
apiVersion: v1
kind: Service 
metadata:
  namespace: expense
  name: backend
  
spec:
  selector:
   app: backend
   tier: api
   project: expense
  ports:
  - name: backend-port
    protocol: TCP
    port: 8080 # this is service port
    targetport: 8080 # this is container port. 